[B
import random                                                                                                                                                                                                                                                                                                                                                                                                       
# Define the game tree node                                                                                                                                                                               
class Node:                                                                                                                                                                                               
    def __init__(self, value, children=None):                                                                                                                                                             
        self.value = value                                                                                                                                                                                
        self.children = children if children else []                                                                                                                                                      
                                                                                                                                                                                                          
# Define the Minimax algorithm with Alpha-Beta Pruning                                                                                                                                                    
def minimax(node, depth, alpha, beta, is_maximizing):                                                                                                                                                     
    if depth == 0 or len(node.children) == 0:                                                                                                                                                             
        return node.value                                                                                                                                                                                 
                                                                                                                                                                                                          
    if is_maximizing:                                                                                                                                                                                     
        value = float('-inf')                                                                                                                                                                             
        for child in node.children:                                                                                                                                                                       
            value = max(value, minimax(child, depth - 1, alpha, beta, False))                                                                                                                             
            alpha = max(alpha, value)                                                                                                                                                                     
            if alpha >= beta:                                                                                                                                                                             
                break  # Beta cut-off                                                                                                                                                                     
        return value                                                                                                                                                                                          else:                                                                                                                                                                                                         value = float('inf')                                                                                                                                                                              
        for child in node.children:                                                                                                                                                                                   value = min(value, minimax(child, depth - 1, alpha, beta, True))                                                                                                                                          beta = min(beta, value)                                                                                                                                                                                   if alpha >= beta:                                                                                                                                                                                             break  # Alpha cut-off                                                                                                                                                                    
        return value                                                                                                                                                                                                                                                                                                                                                                                                # Create a sample game tree                                                                                                                                                                               
root = Node(0)                                                                                                                                                                                            
root.children = [Node(10), Node(20), Node(30)]                                                                                                                                                            
                                                                                                                                                                                                          
# Run the Minimax algorithm with Alpha-Beta Pruning                                                                                                                                                       
best_score = minimax(root, 2, float('-inf'), float('inf'), True)                                                                                                                                          
print("Best score:", best_score)  t
('inf'), True)                                                                                                                                          print("Best score:", best_score) 

